remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Alfred Hunt
description: >- # this means to ignore newlines until "baseurl:"
  Experienced Software Engineer specializing in C++, C#, Java, and Python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
