remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: alfredhunt.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Write your site description here. It will be used by Jekyll and the theme to generate meta descriptions and other relevant info.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
